// The collector table.
//
// Each entry is one MARKUP SHAPE, not one provider — AdSense appears as a script query parameter,
// as a data-ad-client attribute, as a meta tag and as a legacy global assignment, and those are
// four collectors because they are four regexes with four different anchors.
//
// Every pattern was measured against a corpus of live documents (177 pages, 96 ads.txt and
// app-ads.txt files, fetched tag-manager containers, /.well-known/ documents) plus a negative
// corpus of 23 pages and four minified libraries. A pattern that fired in the negative corpus was
// anchored harder or dropped. That is why so many look over-specified: the unanchored version of
// the same pattern mines base64. Measured leak rate across all 121 collectors against the minified
// libraries: zero.
//
// THREE COLLECTORS WERE WRITTEN AND THEN DELETED, and the reasons generalise:
//   - Adsterra's pl<digits> serving subdomain. It is a HOST label that rotates weekly, not an
//     account, so every rotation would have minted a second operator node for one operator.
//   - Google Floodlight's DC- advertiser id. The width came from the catalogue and nothing in
//     350+ corpus documents corroborated it. An unverified pattern is not a cheap bet; it is a
//     node nobody can trace back to bytes.
//   - The generic network referral id. It emits bare digits into the same namespace as ExoClick
//     and JuicyAds zone ids, and nothing in the value distinguishes the two.
export type HitPhase = 'markup' | 'adstxt' | 'wellknown' | 'gtm';

export interface Collector {
    /** Unique; appears in the run log so a bad emit can be traced to one rule. */
    key: string;
    /** Namespace slug for the node value. Empty when `providerFromGroup` supplies it per match. */
    provider: string;
    /** ads.txt names its ad system in field 1, so the provider comes out of the match itself. */
    providerFromGroup?: number;
    /** web.tracking_id `kind`. */
    kind: string;
    /** web.tracking_id `source`. */
    source: string;
    phase: HitPhase;
    /** Regex SOURCE. Compiled per document — never store a compiled `g` regex here. */
    regex: string;
    flags: string;
    /** 1-based capture group holding the raw identifier. */
    group: number;
    /** Whole-document precondition; the collector is skipped when it does not match. */
    pageGuard?: string;
    /** Literal raw values that must never become nodes (hubs, demos, placeholders). */
    reject?: string[];
    rejectRegex?: string;
    /**
     * Case-fold the raw value before it becomes a node.
     *
     * Needed wherever a pattern accepts mixed-case hex or an identifier the issuer treats as
     * case-insensitive. Identity is the value string, so `A1B2` and `a1b2` are two nodes for one
     * account — a split that looks like two operators and is invisible on the canvas.
     */
    normalize?: 'lower';
    /** Percent-decode before emitting. Set on the email collectors: `%40` is common in an href. */
    urldecode?: boolean;
    /**
     * Off unless the caller asks for it.
     *
     * One collector carries this: the ads.txt DIRECT sweep. It is not noisy, it is VOLUMINOUS —
     * measured 7,334 nodes from 88 publisher hosts, a median of 74 per file and 1,637 from the
     * largest. Most of those rows are the publisher's relationship with an ad exchange that ten
     * thousand other publishers also use, and ten food blogs sharing one agency's copied ads.txt
     * produced a 10-way clique of 54 shared nodes that no reject list can prevent. The
     * high-value, low-volume rows in the same file — the publisher's own Google account,
     * OWNERDOMAIN, INVENTORYPARTNERDOMAIN — are separate collectors and stay on.
     */
    optIn?: boolean;
    /** 'email' routes to identity.email_address instead of web.tracking_id. */
    emit?: 'tracking_id' | 'email';
    note: string;
}

/**
 * Provider slugs that name one company twice.
 *
 * Identity is the namespaced value, so two slugs for one issuer split one account into two nodes —
 * the exact failure this type exists to avoid, arrived at from the wrong end. Every pair here was
 * MEASURED as a split, not assumed from brand knowledge:
 *
 *   - monetag / propellerads: zone 2605345 was served under both propu.sh and vaugroar.com on the
 *     same two pages. One zone, two brands.
 *   - google / adsense: an ads.txt DIRECT row gives `pub-…` under the ad-system domain google.com,
 *     while the AdSense tag in the same site's markup gives `ca-pub-…`. Both halves differ, so
 *     `googlePubPrefix` below fixes the value while this map fixes the slug.
 *   - the ads.txt vendor pairs: 145 account ids appeared under two vendor domains for one company
 *     (Sharethrough/Smart AdServer, Telaria/Tremor, SpotX, Sovrn/Lijit, RhythmOne/Unruly,
 *     ucfunnel/Aralego, Adipolo, Yahoo/AOL, LKQD). The canonical side is arbitrary; being
 *     consistent is not.
 */
export const PROVIDER_ALIAS: Record<string, string> = {
    monetag: 'propellerads',
    google: 'adsense',
    'sharethrough.com': 'smartadserver.com',
    'tremorhub.com': 'telaria.com',
    'spotxchange.com': 'spotx.tv',
    'lijit.com': 'sovrn.com',
    'video.unrulymedia.com': 'rhythmone.com',
    'aralego.com': 'ucfunnel.com',
    'adipolosolutions.com': 'adipolo.com',
    'aol.com': 'yahoo.com',
    'lkqd.net': 'lkqd.com',
};

/**
 * The other half of the google/adsense merge: ads.txt writes the account as `pub-…` and the
 * AdSense tag writes the same account as `ca-pub-…`. Restore the prefix so the two converge.
 */
export function googlePubPrefix(provider: string, raw: string): string {
    return provider === 'adsense' && raw.startsWith('pub-') ? `ca-${raw}` : raw;
}

export const COLLECTORS: Collector[] = [
    {
        key: "adstxt_google_pub_id",
        provider: "google",
        kind: "advertising",
        source: "ads_txt",
        phase: "adstxt",
        regex: "^[ \\t ﻿]*[A-Za-z0-9.\\-]+[ \\t]*,[ \\t]*(?:ca-)?(pub-\\d{16})[ \\t]*,[ \\t]*DIRECT(?![A-Za-z0-9_])",
        flags: "gmi",
        group: 1,
        rejectRegex: "^(?:ca-)?pub-0{16}$",
        note: "Line-anchored to field 2 of a DIRECT row per 'where' (the catalogue's bare boundary form would swallow the 2,224 RESELLER pub rows, spread up to 44 files); capture excludes ca- so the ads.txt and AdSense-script forms normalise to one node.",
    },
    {
        key: "adstxt_inventorypartnerdomain",
        provider: "inventorypartnerdomain",
        kind: "other",
        source: "ads_txt",
        phase: "adstxt",
        regex: "^[ \\t ﻿]*INVENTORYPARTNERDOMAIN[ \\t ]*=[ \\t ]*((?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\\.)+(?:xn--[a-z0-9-]{2,59}|[a-z]{2,63}))\\.?[ \\t ]*(?:[#;].*)?\\r?$",
        flags: "gmi",
        group: 1,
        reject: ["example.com"],
        note: "Same line-anchored variable form as OWNERDOMAIN; the anchor is what keeps commented-out '# INVENTORYPARTNERDOMAIN' lines out.",
    },
    {
        key: "adstxt_ownerdomain",
        provider: "ownerdomain",
        kind: "other",
        source: "ads_txt",
        phase: "adstxt",
        regex: "^[ \\t ﻿]*OWNERDOMAIN[ \\t ]*=[ \\t ]*((?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\\.)+(?:xn--[a-z0-9-]{2,59}|[a-z]{2,63}))\\.?[ \\t ]*(?:[#;].*)?\\r?$",
        flags: "gmi",
        group: 1,
        reject: ["example.com"],
        note: "Start-of-line anchor is what dodges the prose/doc line \"'variable record': `OWNERDOMAIN=example.com`\" found inline in a real ads.txt; spec says use only the first instance per file.",
    },
    {
        key: "adstxt_direct_account",
        provider: "",
        providerFromGroup: 1,
        kind: "advertising",
        source: "ads_txt",
        phase: "adstxt",
        regex: "^[ \\t ﻿]*((?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\\.)+(?:xn--[a-z0-9-]{2,59}|[a-z]{2,63}))[ \\t]*,[ \\t]*([A-Za-z0-9](?:[A-Za-z0-9._\\-]{0,62}[A-Za-z0-9])?)[ \\t]*,[ \\t]*DIRECT(?![A-Za-z0-9_])[ \\t ]*(?:,[ \\t]*[A-Za-z0-9._\\-]{0,64}[ \\t ]*)?(?:[,;#].*)?\\r?$",
        flags: "gmi",
        group: 2,
        reject: ["1100004890", "15268", "4016", "4012", "4071", "4073", "4074", "17280", "d42af5b070f04d1585124de5da836367", "7f799d40d2e02a0", "7f799d40d2e02a0-OB", "TNS45R", "22588", "22586", "YE6AJ9", "VjRGXnvZ8HgUOvBai3Om", "4009", "20c9a44b427c40e89d3d7d711dc5b9dc", "8955", "61d88450bdb25bc-OB", "lDF5XleM05", "346012", "157743", "b37ed21aa3e45e7e", "22884", "45128", "193216", "770449", "3050", "B-060910", "O9K1GM", "20616", "20618", "944ae2c3", "5d8ed25e-57cc-441a-b62a-127b34faae4e", "894a3f52ea9e6d4", "DJQVCM", "265720", "21929081050", "8CUV34PJ4", "0098", "dxkulture", "651", "26094", "11901", "2e7e1587-d92f-46dd-8721-80b53eccb87e", "105199380", "62f40acb3086a26", "62ff8a580aaea32", "EYHMU2", "3664", "159855", "B-062476", "1MCYGZ", "2271", "775f9dcfac64c3b", "775f9dcfac64c3b-OB", "23897", "30882", "15156", "101121", "vFUHFYXoNp", "323-b6067", "B-060253", "280159-eb", "395866-eb", "396247-eb", "25104", "8CU6LTV07", "8CUB9Z18O", "8cu28b361", "8CUPEPKI9", "8947", "265720-eb", "UvcAx8IL", "aRE1degH", "946176315", "20687", "105199584", "LVXCEA", "18680", "GJXPHY", "7207", "7207-EB", "7d80e32acc45b49", "551349", "551349-eb", "06EhCbcfZK", "13510", "8CU92WUF1", "852c0d87-cafc-4bba-a88c-f74cf18086b0", "12918514-294e-4e6e-8eae-c89a8fec20f5", "4194", "192585", "16114", "357", "22861843909", "9533", "790", "24712"],
        rejectRegex: "^(?:ca-)?pub-\\d{16}$",
        optIn: true,
        note: "Line-anchored, DIRECT-only, \\r?$ and NBSP/BOM tolerant, trailing # comment absorbed; rejects pub- accounts so google rows mint the bare pub- node instead of google.com:pub-.",
    },
    {
        key: "gtm_body_ca_pub",
        provider: "adsense",
        kind: "advertising",
        source: "tag_manager_container",
        phase: "gtm",
        regex: "\\b(ca-pub-[0-9]{16})\\b",
        flags: "g",
        group: 1,
        reject: ["ca-pub-0000000000000000", "ca-pub-1234567890123456"],
        rejectRegex: "^ca-pub-([0-9])\\1{15}$",
        emit: "tracking_id",
        note: "The bare ca-pub- scan entry 30 forbids in markup is fine here: the fetched document is Google's own container and ca-pub- is self-anchoring (never matches inside ca-host-pub- or mix-pub-).",
    },
    {
        key: "gtm_body_aw",
        provider: "google_ads",
        kind: "advertising",
        source: "tag_manager_container",
        phase: "gtm",
        regex: "\\b(AW-(?!123456789\\b)[0-9]{9,11})\\b",
        flags: "g",
        group: 1,
        reject: ["AW-123456789"],
        emit: "tracking_id",
        note: "Google Ads account named only inside the container — the highest-value yield of the second hop, since an AW- account has a verified payment method behind it.",
    },
    {
        key: "gtm_body_ga4",
        provider: "google_analytics",
        kind: "analytics",
        source: "tag_manager_container",
        phase: "gtm",
        regex: "(?<![A-Za-z0-9+/_-])(G-(?![0-9]{10})[A-Z0-9]{10})(?![A-Za-z0-9+/=_-])",
        flags: "g",
        group: 1,
        rejectRegex: "^G-([A-Z0-9])\\1{4,}$",
        emit: "tracking_id",
        note: "Second-hop: runs on the separately fetched gtm.js/gtag/js container body, which is static JS needing no execution; entry 28's all-digit exclusion added, plus entry 27's explicit delimiters instead of \\b because the container is minified.",
    },
    {
        key: "gtm_body_ua",
        provider: "google_analytics",
        kind: "analytics",
        source: "tag_manager_container",
        phase: "gtm",
        regex: "\\b(UA-[0-9]{4,10}-[1-9][0-9]{0,2})\\b",
        flags: "g",
        group: 1,
        emit: "tracking_id",
        note: "No pageGuard here — the fetched document IS the Google measurement marker, so the markup-phase guard is redundant.",
    },
    {
        key: "gtm_body_gt",
        provider: "google_tag",
        kind: "tag_manager",
        source: "tag_manager_container",
        phase: "gtm",
        regex: "\\b(GT-[A-Z0-9]{6,10})\\b",
        flags: "g",
        group: 1,
        rejectRegex: "^GT-(.)\\1+$",
        emit: "tracking_id",
        note: "Bare GT- sweep is safe ONLY in this phase — a Google container has no phone-catalogue prose; the same regex on markup mints Samsung model numbers, which is why the markup GT- collectors are anchored.",
    },
    {
        key: "gtm_body_gtm",
        provider: "google_tag_manager",
        kind: "tag_manager",
        source: "tag_manager_container",
        phase: "gtm",
        regex: "\\b(GTM-[A-Z0-9]{6,9})\\b",
        flags: "g",
        group: 1,
        rejectRegex: "^GTM-(?:([A-Z0-9])\\1{5,8}|ABCDEF(?:GH?)?)$",
        emit: "tracking_id",
        note: "Nested/chained container ids inside the fetched body; {6,9} per entry 32's measured range, not entry 28's {5,9}, which would only widen the FP surface.",
    },
    {
        key: "la51_init_obj",
        provider: "51la",
        kind: "analytics",
        source: "inline_script",
        phase: "markup",
        regex: "\\{(?=[^{}]{0,300}\\bck\\s*:\\s*[\"'])[^{}]{0,300}?\\bid\\s*:\\s*[\"']([A-Za-z0-9_-]{6,64})[\"']",
        flags: "g",
        group: 1,
        pageGuard: "\\b51\\.la\\b",
        emit: "tracking_id",
        note: "Loader-config object literal (window.LA.init({id,ck})) — bare object sweep, so pageGuard requiring 51.la on the page is mandatory per HARD RULE 2.",
    },
    {
        key: "la51_sdk_src",
        provider: "51la",
        kind: "analytics",
        source: "script_src",
        phase: "markup",
        regex: "sdk\\.51\\.la/js-sdk-pro\\.min\\.js\\?(?:[^\"'\\s<>]*&)?id=([A-Za-z0-9_-]{6,64})",
        flags: "g",
        group: 1,
        emit: "tracking_id",
        note: "Anchored on vendor host + exact SDK filename + id= query param; charset deliberately loose because the catalogue disclaims any length/charset evidence.",
    },
    {
        key: "la51_users_legacy",
        provider: "51la",
        kind: "analytics",
        source: "script_src",
        phase: "markup",
        regex: "\\bjs\\.users\\.51\\.la/(\\d{4,12})\\.js",
        flags: "g",
        group: 1,
        emit: "tracking_id",
        note: "Legacy numeric-id script src; digits are anchored between the vendor host path and the .js suffix, never swept bare.",
    },
    {
        key: "admaven_placement_meta",
        provider: "admaven",
        kind: "advertising",
        source: "meta_tag",
        phase: "markup",
        regex: "<meta\\b(?=[^>]*\\bname\\s*=\\s*[\"']?admaven-placement(?![-\\w]))[^>]*?[\\s\"'](?<![-\\w])content\\s*=\\s*([\"']?)([A-Za-z0-9_.:-]{3,64})\\1(?=[\\s/>])",
        flags: "gi",
        group: 2,
        note: "meta name=admaven-placement; quote optional because the live sample is unquoted content=BqHgGpjg7> - group 1 is the quote backreference, group 2 is the value",
    },
    {
        key: "adsense_pub_id_meta",
        provider: "adsense",
        kind: "advertising",
        source: "meta_tag",
        phase: "markup",
        regex: "<meta\\b(?=[^>]*google-adsense-account)[^>]*?content\\s*=\\s*[\"']?(ca-pub-[0-9]{16})(?![0-9])",
        flags: "gi",
        group: 1,
        reject: ["ca-pub-0000000000000000", "ca-pub-1234567890123456"],
        rejectRegex: "^ca-pub-([0-9])\\1{15}$",
        emit: "tracking_id",
        note: "Lookahead asserts the marker anywhere inside the same tag, so it survives either attribute order in one pass; [^>]*? keeps the scan inside the tag. The only AdSense shape that survives a script-strip.",
    },
    {
        key: "adsense_pub_id_tag",
        provider: "adsense",
        kind: "advertising",
        source: "script_src",
        phase: "markup",
        regex: "(?:adsbygoogle\\.js\\?[^\"'\\s<>]{0,200}?\\bclient=|data-ad-client\\s*=\\s*[\"']?|google_ad_client\\s*[:=]\\s*[\"'])(ca-pub-[0-9]{16})(?![0-9])",
        flags: "g",
        group: 1,
        reject: ["ca-pub-0000000000000000", "ca-pub-1234567890123456"],
        rejectRegex: "^ca-pub-([0-9])\\1{15}$",
        emit: "tracking_id",
        note: "TWO CORRECTIONS to pat, both measured: [?&]client= demanded a second separator and matched nothing (where's \\bclient= is right, same bug entry 29 fixed for iu=), and the live legacy form is google_ad_client: \"…\" with a COLON, so [:=]; data-ad-client accepts single, double and bare quotes; (?![0-9]) not \\b so ca-pub-…_v2 survives.",
    },
    {
        key: "adsterra_atoptions_key",
        provider: "adsterra",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "atOptions\\s*=\\s*\\{[^{}]{0,200}?['\"]key['\"]\\s*:\\s*['\"]([0-9a-f]{32})['\"]",
        flags: "g",
        group: 1,
        rejectRegex: "^0+$",
        note: "inline atOptions block; case-SENSITIVE deliberately - atOptions is a JS identifier and the key is lowercase hex, adding i would open a bare 32-hex to base64 and minified-bundle noise",
    },
    {
        key: "adsterra_invoke_key",
        provider: "adsterra",
        kind: "advertising",
        source: "script_src",
        phase: "markup",
        regex: "/([0-9a-f]{32})/invoke\\.js",
        flags: "g",
        group: 1,
        rejectRegex: "^0+$",
        note: "same key via the URL path, which survives LiteSpeed rewriting src= to data-src=; kept as its own shape because pages carry the invoke URL with no atOptions block at all",
    },
    {
        key: "adsterra_socialbar_key",
        provider: "adsterra",
        kind: "advertising",
        source: "script_src",
        phase: "markup",
        regex: "//pl\\d{6,10}\\.(?:[a-z0-9-]+\\.)+[a-z]{2,}/([0-9a-f]{2})/([0-9a-f]{2})/([0-9a-f]{2})/(\\1\\2\\3[0-9a-f]{26})\\.js",
        flags: "g",
        group: 4,
        rejectRegex: "^0+$",
        note: "Social Bar split-hex URL; the three path bytes are re-used as backreferences so path[0:2]+[3:5]+[6:8]==key[0:6] is enforced by the regex itself rather than by a post-check",
    },
    {
        key: "amazon_associates_tag",
        provider: "amazon_associates",
        kind: "affiliate",
        source: "html_link",
        phase: "markup",
        regex: "(?<![\\w.-])(?:(?:www\\.)?amazon\\.(?:com\\.au|com\\.br|com\\.mx|com\\.tr|com\\.be|co\\.uk|co\\.jp|co\\.za|com|de|fr|it|es|ca|in|nl|se|pl|sg|ae|sa|eg|ie)|[a-z0-9-]+\\.amazon-adsystem\\.com)\\\\?\\/[^\"'\\s<>:]{0,300}?[?&](?:tag|t)=([A-Za-z0-9][A-Za-z0-9-]{1,28}-\\d{2})(?![\\w-])",
        flags: "gi",
        group: 1,
        note: "tag= must be anchored to an amazon.<tld>/amazon-adsystem host; bare [?&]tag= hits ordinary blog tag params. Uses a lookbehind (V8/JSC fine, Safari <16.4 would throw)",
    },
    {
        key: "awin_publisher_id",
        provider: "awin",
        kind: "affiliate",
        source: "html_link",
        phase: "markup",
        regex: "https?:\\/\\/(?:www\\.)?awin1\\.com\\/(?:cread|awclick)\\.php\\?(?:[^\"'\\s<>]*?[&;])?awinaffid=(\\d{3,9})(?!\\d)",
        flags: "g",
        group: 1,
        note: "awinaffid is the publisher account, awinmid is the merchant. pclick.php dropped — its affiliate param is a=, unconfirmed, and guessing a bare single-letter param is how you key on the wrong entity",
    },
    {
        key: "baidu_tongji_hm",
        provider: "baidu_tongji",
        kind: "analytics",
        source: "inline_script",
        phase: "markup",
        regex: "hm\\.baidu\\.com\\\\?/(?:hm|h)\\.js\\?([0-9a-f]{32})(?![0-9a-f])",
        flags: "g",
        group: 1,
        emit: "tracking_id",
        note: "32-lowercase-hex anchored to the hm.baidu.com URL; optional \\\\ before / handles the JS-string-escaped \"https:\\/\\/hm.baidu.com\\/hm.js?\" form, and deliberately NO /i so uppercase hex inside base64 cannot match.",
    },
    {
        key: "beusable_rum_id",
        provider: "beusable",
        kind: "analytics",
        source: "inline_script",
        phase: "markup",
        regex: "\\brum\\.beusable\\.net/(?:load|script)/(b\\d{6}e\\d{6}u\\d+)",
        flags: "gi",
        group: 1,
        emit: "tracking_id",
        note: "b<YYMMDD>e<HHMMSS>u<seq> shape anchored on the vendor host; /script/ arm stops at the id so the trailing per-site token is not captured.",
    },
    {
        key: "msvalidate_meta",
        provider: "bing_webmaster",
        kind: "site_verification",
        source: "meta_tag",
        phase: "markup",
        regex: "<meta\\b(?=[^>]*\\bname=[\"']?msvalidate\\.01)[^>]*\\bcontent=[\"']([0-9A-Fa-f]{32})[\"']",
        flags: "gi",
        group: 1,
        normalize: "lower",
        note: "One lookahead inside the tag covers both attribute orders with a single group, and [^>]* keeps the match from crossing into the next tag.",
    },
    {
        key: "crypto_btc_bech32_bare",
        provider: "bitcoin",
        kind: "payment",
        source: "other",
        phase: "markup",
        regex: "\\b(bc1(?:[02-9ac-hj-np-z]{39}|[02-9ac-hj-np-z]{59}))\\b",
        flags: "g",
        group: 1,
        note: "length-anchored to real witness programs (42=P2WPKH, 62=P2WSH/P2TR); {11,71} is too loose. No bare legacy base58 and no bare 0x[0-9a-f]{40} at all, per the entry's measured FP finding",
    },
    {
        key: "clarity_inline_loader",
        provider: "clarity",
        kind: "analytics",
        source: "inline_script",
        phase: "markup",
        regex: "\\\\*[\"']clarity\\\\*[\"']\\s*,\\s*\\\\*[\"']script\\\\*[\"']\\s*,\\s*\\\\*[\"']([a-z0-9]{8,12})\\\\*[\"']",
        flags: "g",
        group: 1,
        note: "case-SENSITIVE on purpose — clarity.ms 400s uppercase ids, so an i flag could only ever capture invalid values. \\\\* absorbs Next.js/RSC flight escaping at depth 1 or 3. The (window,document, prefix is dropped, it adds nothing",
    },
    {
        key: "clarity_tag_url",
        provider: "clarity",
        kind: "analytics",
        source: "script_src",
        phase: "markup",
        regex: "(?:https?:)?\\/\\/(?:www\\.)?clarity\\.ms\\/tag\\/([a-z0-9]{8,12})(?![a-z0-9])",
        flags: "g",
        group: 1,
        note: "hardcoded/server-rendered URL; protocol-relative accepted because Microsoft's own Joomla plugin emits '//www.clarity.ms/tag/'. (?![a-z0-9]) not \\b so ?ref=bwt terminates cleanly while a 13-char token still fails closed",
    },
    {
        key: "clickadilla_admpid",
        provider: "clickadilla",
        kind: "advertising",
        source: "script_src",
        phase: "markup",
        regex: "\\bdata-admpid\\s*=\\s*[\"']?(\\d{3,9})(?!\\d)",
        flags: "gi",
        group: 1,
        pageGuard: "wpadmngr\\.com|_CAdM|adManager(?:\\.m)?\\.js",
        rejectRegex: "^0+$",
        note: "publisher id on the adManager script tag, gated on the wpadmngr/_CAdM/adManager marker per entry 23 rule 4",
    },
    {
        key: "clickbank_hoplink_host",
        provider: "clickbank",
        kind: "affiliate",
        source: "html_link",
        phase: "markup",
        regex: "(?:^|[^a-z0-9._-])([a-z0-9]{2,25})\\.([a-z0-9]{2,25})\\.hop\\.clickbank\\.net(?![a-z0-9.-])",
        flags: "gi",
        group: 1,
        reject: ["youraffid", "youraffiliate", "affiliateid", "affiliate", "nickname", "yournickname", "yourid", "affid", "xxxxx"],
        note: "<affiliate>.<vendor>.hop.clickbank.net; group 1 only — group 2 is the vendor, context never a node. Affiliate group REQUIRED (the entry's fatal bug), no scheme required, guards replace \\b",
    },
    {
        key: "clickbank_hoplink_query",
        provider: "clickbank",
        kind: "affiliate",
        source: "html_link",
        phase: "markup",
        regex: "hop\\.clickbank\\.net\\/\\?(?:[^\"'\\s<>]{0,300}?[&;])?affiliate=([a-z0-9]{2,25})(?![a-z0-9])",
        flags: "gi",
        group: 1,
        reject: ["youraffid", "youraffiliate", "affiliateid", "affiliate", "nickname", "yournickname", "yourid", "affid", "xxxxx"],
        note: "CORRECTED the entry's pat: it consumed the ? then demanded a second [?&], so it could never match affiliate= as the first param — which is exactly the form 'where' documents. Made the separator group optional",
    },
    {
        key: "coupang_partners_tracking",
        provider: "coupang_partners",
        kind: "affiliate",
        source: "inline_script",
        phase: "markup",
        regex: "(?:trackingCode\\W{0,3}[:=]\\W{0,3}|[?&](?:lptag|trackingCode)=)(AF\\d{6,10})(?!\\d)",
        flags: "g",
        group: 1,
        emit: "tracking_id",
        note: "Both shapes in one alternation (PartnersCoupang.G trackingCode + ?lptag= deep link); the anchor is mandatory because bare AF+7digits occurs in unrelated prose.",
    },
    {
        key: "criteo_set_account",
        provider: "criteo",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "[\"']?event[\"']?\\s*:\\s*([\"'])setAccount\\1\\s*,\\s*[\"']?account[\"']?\\s*:\\s*([\"']?)(\\d{3,12})\\2(?!\\d)",
        flags: "g",
        group: 3,
        emit: "tracking_id",
        note: "Requires the event:setAccount / account: pair adjacently because the value is a bare 5-digit integer; quote group \\2 backreferences so quoted and unquoted account forms both work.",
    },
    {
        key: "exoclick_idzone_url",
        provider: "exoclick",
        kind: "advertising",
        source: "other",
        phase: "markup",
        regex: "(?:\\b(?:magsrv|exdynsrv|exosrv|pemsrv|realsrv|orbsrv|optnx|exv6|opoxv)\\.com|/(?:v1/)?(?:vast|splash|popunder|video)\\.php)[^\"'\\s<>]{0,300}?[?&](?:amp;)?idzone=(\\d{5,9})(?!\\d)",
        flags: "gi",
        group: 1,
        reject: ["12345", "123456", "1234567"],
        rejectRegex: "^0+$",
        note: "idzone inside a VAST/splash serving URL, anchored on the ExoClick host or the vast/splash path; must also run against the percent-decoded copy",
    },
    {
        key: "exoclick_ins_zoneid",
        provider: "exoclick",
        kind: "advertising",
        source: "html_link",
        phase: "markup",
        regex: "<ins\\b(?=[^>]*\\bclass\\s*=\\s*[\"']eas6a97888e\\d*[\"'])(?=[^>]*\\bdata-zoneid\\s*=\\s*[\"'](\\d{4,9})[\"'])",
        flags: "gi",
        group: 1,
        reject: ["1111", "2222", "3333", "12345", "123456", "1234567"],
        rejectRegex: "^0+$",
        note: "order-independent lookaheads on the ins placeholder; class is eas6a97888e\\d* because the suffix varies, and no type= is required because Rocket Loader rewrites it",
    },
    {
        key: "exoclick_popmagic_idzone",
        provider: "exoclick",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "(?<!\\w)(?:[\"']?idzone[\"']?|data-zoneid)\\s*[:=]\\s*[\"']?(\\d{5,10})(?!\\d)",
        flags: "g",
        group: 1,
        pageGuard: "popMagic|exdynsrv\\.com|exosrv\\.com|exoclick\\.com|opoxv\\.com|exacdn\\.com|pemsrv\\.com|eas6a97888e2",
        reject: ["12345", "123456", "1234567"],
        rejectRegex: "^0+$",
        note: "bare idzone is too loose alone so the document must carry popMagic or a licensed ExoClick host; the reject values are ExoClick's OWN published doc placeholders, measured as a live false positive",
    },
    {
        key: "exoclick_site_verification_meta",
        provider: "exoclick",
        kind: "advertising",
        source: "meta_tag",
        phase: "markup",
        regex: "<meta\\b(?=[^>]*\\bname\\s*=\\s*[\"']?(?:exoclick|6a97888e)-site-verification(?![-\\w]))[^>]*?[\\s\"'](?<![-\\w])content\\s*=\\s*[\"']?([0-9a-fA-F]{32})(?![0-9a-fA-F])",
        flags: "gi",
        group: 1,
        rejectRegex: "^0+$",
        normalize: "lower",
        note: "both meta spellings, the plain one and the ad-block-evading 6a97888e- alias; quotes optional because the wild form is unquoted",
    },
    {
        key: "gam_network_amp_slot",
        provider: "google_ad_manager",
        kind: "advertising",
        source: "other",
        phase: "markup",
        regex: "data-slot=[\"'](/[0-9]{4,12}(?:,[0-9]{1,12})?/)",
        flags: "gi",
        group: 1,
        reject: ["/6355419/", "/1234567/", "/123456789/", "/6062/"],
        emit: "tracking_id",
        note: "AMP amp-ad shape; the required /digits/ is what separates it from shadcn's data-slot=\"button\"/\"icon\" and from AdSense's data-slot=\"8920522022\".",
    },
    {
        key: "gam_network_defineslot",
        provider: "google_ad_manager",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "\\bdefine(?:OutOfPage)?Slot\\s*\\(\\s*[\"'](/[0-9]{4,12}(?:,[0-9]{1,12})?/)",
        flags: "g",
        group: 1,
        reject: ["/6355419/", "/1234567/", "/123456789/", "/6062/"],
        emit: "tracking_id",
        note: "Capture group carries BOTH slashes so the raw is self-naming (/7346874/, never bare 7346874) and the MCM child is inside the group, so /1234567,1234/ cannot collapse onto the parent's node; body needs \\/ and %2F normalised to / before this runs.",
    },
    {
        key: "gam_network_gampad_iu",
        provider: "google_ad_manager",
        kind: "advertising",
        source: "other",
        phase: "markup",
        regex: "(?:securepubads|pubads)\\.g\\.doubleclick\\.net/gampad/(?:live/)?(?:ads|clk)[^\"'\\s]{0,400}?(?:[?&]|\\\\u0026)iu=(/[0-9]{4,12}(?:,[0-9]{1,12})?/)",
        flags: "gi",
        group: 1,
        reject: ["/6355419/", "/1234567/", "/123456789/", "/6062/"],
        emit: "tracking_id",
        note: "MEASURED FIX beyond the catalogue: the one live sample writes the separator as &, so [?&] alone matched nothing — the alternation restores it; the doubleclick host is what stops iu= matching minified code.",
    },
    {
        key: "google_ads_aw_id",
        provider: "google_ads",
        kind: "advertising",
        source: "other",
        phase: "markup",
        regex: "\\b(AW-(?!123456789\\b)[0-9]{9,11})\\b",
        flags: "g",
        group: 1,
        reject: ["AW-123456789"],
        emit: "tracking_id",
        note: "Case-SENSITIVE whole-body sweep per pat; it strictly subsumes the three anchored confirmers (config / loader id= / send_to), so those are not separate collectors, and the value never includes the /conversion_label suffix.",
    },
    {
        key: "ga4_bare_strict",
        provider: "google_analytics",
        kind: "analytics",
        source: "other",
        phase: "markup",
        regex: "(?<![A-Za-z0-9+/_-])(G-[A-Z0-9]{10})(?![A-Za-z0-9+/=_-])",
        flags: "g",
        group: 1,
        reject: ["G-XXXXXXXXXX"],
        rejectRegex: "^G-([A-Z0-9])\\1{4,}$",
        emit: "tracking_id",
        note: "Strict {10} whole-body tier with explicit delimiters instead of \\b: leading = allowed (?id=G-…), trailing = excluded as base64 padding; case-SENSITIVE, no /i.",
    },
    {
        key: "ga4_gtag_config_call",
        provider: "google_analytics",
        kind: "analytics",
        source: "inline_script",
        phase: "markup",
        regex: "gtag\\(\\s*[\"']config[\"']\\s*,\\s*[\"'](G-[A-Z0-9]{6,12})[\"']",
        flags: "g",
        group: 1,
        reject: ["G-XXXXXXXXXX"],
        rejectRegex: "^G-([A-Z0-9])\\1{4,}$",
        emit: "tracking_id",
        note: "gtag('config', …) call shape; the literal gtag( + 'config' pair is the anchor, so a bare G- token in prose or a bundle cannot reach it.",
    },
    {
        key: "ga4_gtag_loader_id",
        provider: "google_analytics",
        kind: "analytics",
        source: "script_src",
        phase: "markup",
        regex: "googletagmanager\\.com/gtag/js\\?[^\"'\\s]*\\bid=(G-[A-Z0-9]{6,12})\\b",
        flags: "g",
        group: 1,
        reject: ["G-XXXXXXXXXX"],
        rejectRegex: "^G-([A-Z0-9])\\1{4,}$",
        emit: "tracking_id",
        note: "Anchored on the gtag/js loader host+path so the loose {6,12} tier is safe; \\bid= (not [?&]id=) so ?id= and &id= both hit and sid=/gtm_id= do not.",
    },
    {
        key: "ga4_measurement_id_json",
        provider: "google_analytics",
        kind: "analytics",
        source: "inline_script",
        phase: "markup",
        regex: "[\"']measurementId[\"']\\s*:\\s*[\"'](G-[A-Z0-9]{6,12})[\"']",
        flags: "g",
        group: 1,
        reject: ["G-XXXXXXXXXX"],
        rejectRegex: "^G-([A-Z0-9])\\1{4,}$",
        emit: "tracking_id",
        note: "Inline Firebase/JSON config key, not a tag at all — quoted key name is the whole anchor.",
    },
    {
        key: "ua_tracking_id",
        provider: "google_analytics",
        kind: "analytics",
        source: "other",
        phase: "markup",
        regex: "\\b(UA-[0-9]{4,10}-[1-9][0-9]{0,2})\\b",
        flags: "g",
        group: 1,
        pageGuard: "google-analytics\\.com|googletagmanager\\.com|_setAccount|_gaq|analytics\\.js|ga\\.js|gtag\\(",
        reject: ["UA-XXXXXX-Y", "UA-000000-1"],
        emit: "tracking_id",
        note: "Whole-body sweep gated by one page-level Google-measurement boolean; case-SENSITIVE so kebab-case ua-* class names cannot match. Store the full string — the account half before the dash is the pivot.",
    },
    {
        key: "google_tag_gt_anchored",
        provider: "google_tag",
        kind: "tag_manager",
        source: "other",
        phase: "markup",
        regex: "(?:/gtag/js\\?[^\"'\\s]{0,300}\\bid=|gtag\\(\\s*[\"']config[\"']\\s*,\\s*[\"'])(GT-[A-Z0-9]{6,12})\\b",
        flags: "g",
        group: 1,
        reject: ["GT-XXXXXXXXX"],
        rejectRegex: "^GT-(.)\\1+$",
        emit: "tracking_id",
        note: "NEVER bare — the two gtag anchors are the only thing separating a Google tag from a Samsung model number; case-SENSITIVE.",
    },
    {
        key: "google_tag_ids_json_array",
        provider: "google_tag",
        kind: "tag_manager",
        source: "inline_script",
        phase: "markup",
        regex: "google_tag_ids[^\\]]{0,80}?(GT-[A-Z0-9]{6,12})\\b",
        flags: "g",
        group: 1,
        reject: ["GT-XXXXXXXXX"],
        rejectRegex: "^GT-(.)\\1+$",
        emit: "tracking_id",
        note: "MEASURED ADDITION, not in the catalogue: Shopify emits \"google_tag_ids\":[\"GT-…\",\"G-…\"] with no gtag anchor; the key name is the anchor and [^\\]]{0,80} keeps it inside the array through any escaping depth.",
    },
    {
        key: "gtm_container_id",
        provider: "google_tag_manager",
        kind: "tag_manager",
        source: "other",
        phase: "markup",
        regex: "\\b(GTM-[A-Z0-9]{6,9})\\b",
        flags: "g",
        group: 1,
        reject: ["GTM-ABCDEFGH", "GTM-XXXXXXX"],
        rejectRegex: "^GTM-(?:([A-Z0-9])\\1{5,8}|ABCDEF(?:GH?)?)$",
        emit: "tracking_id",
        note: "Whole-body sweep per entry 32 (containers hide in unrelated JSON), case-SENSITIVE; the captured token must itself satisfy the shape, which is what defeats the gfuel 'id=GTM' junk-capture trap.",
    },
    {
        key: "histats_gif_noscript",
        provider: "histats",
        kind: "analytics",
        source: "script_src",
        phase: "markup",
        regex: "(?:https?:)?\\/\\/(?:[a-z0-9-]+\\.)*histats\\.com\\/0\\.gif\\?([1-9]\\d{0,8})(?=[&\"'\\s])",
        flags: "gi",
        group: 1,
        note: "JS-free noscript counter gif; site id is the first query token, subdomain-agnostic (sstatic1./s10.)",
    },
    {
        key: "histats_start_inline",
        provider: "histats",
        kind: "analytics",
        source: "inline_script",
        phase: "markup",
        regex: "Histats\\.start\\s*(?:\\(\\s*|[\"']\\s*,\\s*[\"'])\\d+\\s*,\\s*([1-9]\\d{0,8})\\s*,",
        flags: "g",
        group: 1,
        note: "site id is the SECOND comma field of Histats.start; the rest of that string is counter display config (size/colour) and is never an identifier — never key on the whole string",
    },
    {
        key: "hotjar_hjsettings_hjid",
        provider: "hotjar",
        kind: "analytics",
        source: "inline_script",
        phase: "markup",
        regex: "_hjSettings\\s*=\\s*\\{[^{}]{0,120}?\\bhjid\\s*:\\s*['\"]?(\\d{4,9})['\"]?",
        flags: "g",
        group: 1,
        note: "the _hjSettings object is the only anchor a bare 7-digit int can have; static.hotjar.com/c/hotjar-<id>.js is concatenated at runtime and is never in served markup, so matching that URL yields nothing",
    },
    {
        key: "impact_publisher_id",
        provider: "impact",
        kind: "affiliate",
        source: "html_link",
        phase: "markup",
        regex: "https?:\\/\\/(?:[a-z0-9-]+\\.)*(?:sjv\\.io|pxf\\.io|7eer\\.net|ojrq\\.net|evyy\\.net|i\\d{5,7}\\.net|impactradius\\.com)(?::\\d+)?\\/c\\/(\\d{4,9})\\/\\d+\\/\\d+",
        flags: "gi",
        group: 1,
        note: "the host allowlist is mandatory — a bare /c/<d>/<d>/<d> matches ordinary site paths. Only the first segment is the publisher account, the other two are the merchant's ad and campaign. prf.hn is Partnerize and is deliberately not folded in",
    },
    {
        key: "juicyads_adzone_push",
        provider: "juicyads",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "adsbyjuicy[\\s\\S]{0,80}?\\badzone\\b[\"']?\\s*:\\s*[\"']?(\\d{5,9})",
        flags: "g",
        group: 1,
        rejectRegex: "^0+$",
        note: "self-gated on the vendor-unique token adsbyjuicy within 80 chars; the push is usually inside a percent-encoded data:text/javascript URI so it only fires after the tolerant decode pass",
    },
    {
        key: "juicyads_ins_id",
        provider: "juicyads",
        kind: "advertising",
        source: "html_link",
        phase: "markup",
        regex: "<ins\\b(?=[^>]*\\bdata-width)[^>]*\\bid=[\"'](\\d{5,9})[\"']",
        flags: "g",
        group: 1,
        pageGuard: "(?:poweredby\\.)?jads\\.co|(?:adserver|js)\\.juicyads\\.com",
        rejectRegex: "^0+$",
        note: "raw-bytes path that survives minification and a failed decode; bare <ins id=digits> is too generic, so the data-width lookahead plus the jads host guard carry the specificity",
    },
    {
        key: "juicyads_pop_token",
        provider: "juicyads",
        kind: "advertising",
        source: "script_src",
        phase: "markup",
        regex: "//js\\.juicyads\\.com/jp\\.php\\?c=([0-9a-z]{16,})",
        flags: "gi",
        group: 1,
        note: "popunder account token anchored on the vendor host and script name; run on raw and percent-decoded copies then dedupe by value",
    },
    {
        key: "juicyads_site_verification_meta",
        provider: "juicyads",
        kind: "advertising",
        source: "meta_tag",
        phase: "markup",
        regex: "<meta\\b(?=[^>]*\\bname\\s*=\\s*[\"']?juicyads-site-verification(?![-\\w]))[^>]*?[\\s\"'](?<![-\\w])content\\s*=\\s*[\"']?(?<![0-9a-f])([0-9a-f]{28,40})(?![0-9a-f])",
        flags: "gi",
        group: 1,
        rejectRegex: "^0+$",
        normalize: "lower",
        note: "length band 28-40 rather than exactly 32 because the where-clause records a truncated 31-char paste in the wild; pat said 32, where wins",
    },
    {
        key: "kakao_adfit_unit",
        provider: "kakao_adfit",
        kind: "advertising",
        source: "other",
        phase: "markup",
        regex: "\\b(DAN-[A-Za-z0-9]{12,20})\\b",
        flags: "g",
        group: 1,
        pageGuard: "kakao_ad_area|kas/static/ba\\.min\\.js",
        emit: "tracking_id",
        note: "Bare DAN- sweep because the vendor template writes data-ad-unit = \"…\" with spaces, so the attribute cannot be the anchor; the DAN- literal plus the mandatory pageGuard are the anchor. Case-SENSITIVE, never /i.",
    },
    {
        key: "kakao_pixel_track_id",
        provider: "kakao_pixel",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "kakaoPixel\\(\\s*\\\\?[\"'](\\d{17,20})\\\\?[\"']",
        flags: "g",
        group: 1,
        emit: "tracking_id",
        note: "Anchored on the kakaoPixel( call and stops before the closing paren so chained .pageView()/.completeRegistration() cannot break it; optional \\\\ handles the JSON-escaped \\\" form.",
    },
    {
        key: "kofi_page_url",
        provider: "ko_fi",
        kind: "payment",
        source: "html_link",
        phase: "markup",
        regex: "https?:\\/\\/(?:www\\.)?ko-fi\\.com\\/([A-Za-z0-9_-]{3,40})(?=[\\/?#'\"\\s<>)\\]]|$)",
        flags: "g",
        group: 1,
        reject: ["about", "api", "blog", "c", "checkout", "contact", "discover", "explore", "faq", "gold", "help", "home", "img", "login", "manage", "post", "privacy", "s", "settings", "signup", "static", "summary", "terms", "w", "widgets"],
        note: "compare reject lowercased. kind is payment not other, per the entry. The asset-extension rule needs no separate check: the trailing lookahead already refuses widget_2.js because '.' is not a boundary char",
    },
    {
        key: "kofi_widget2_init",
        provider: "ko_fi",
        kind: "payment",
        source: "inline_script",
        phase: "markup",
        regex: "kofiwidget2\\.init\\(\\s*['\"][^'\"]{0,80}['\"]\\s*,\\s*['\"]#?[0-9a-fA-F]{3,8}['\"]\\s*,\\s*['\"]([A-Za-z0-9_-]{3,40})['\"]",
        flags: "g",
        group: 1,
        normalize: "lower",
        note: "legacy widget: handle is the 3rd arg, after label and hex colour. Same value space as the URL form so it converges on one node. Vendor-source-confirmed, not field-confirmed (ko-fi.com 403s)",
    },
    {
        key: "kofi_widget_overlay",
        provider: "ko_fi",
        kind: "payment",
        source: "inline_script",
        phase: "markup",
        regex: "kofiWidgetOverlay\\.draw\\(\\s*['\"]([A-Za-z0-9_-]{3,40})['\"]",
        flags: "g",
        group: 1,
        note: "the CURRENT overlay widget, absent from the original entry; handle is the 1st arg. Converges on the same node as kofi_page_url",
    },
    {
        key: "linkedin_insight_pixel_url",
        provider: "linkedin",
        kind: "advertising",
        source: "script_src",
        phase: "markup",
        regex: "(?:https?:)?\\/\\/px\\.ads\\.linkedin\\.com\\/collect\\/?[^\"'`<>\\s]*?[?&](?:amp;)?pid=(\\d{3,10})(?!\\d)",
        flags: "g",
        group: 1,
        note: "JS-free noscript img, the form that survives everything; &amp;-escaped separator tolerated. A 5-digit int mandates this host anchor",
    },
    {
        key: "linkedin_partner_id_inline",
        provider: "linkedin",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "_linkedin_(?:partner_id\\s*=|data_partner_ids\\s*(?:=\\s*\\[|\\.push\\())\\s*[\"'](\\d{3,10})[\"']",
        flags: "g",
        group: 1,
        note: "merges the entry's two inline alternatives into one capture group so the schema's single group index still works; quotes required so the common push(_linkedin_partner_id) variable form is skipped rather than mis-captured",
    },
    {
        key: "meta_pixel_fbq_init",
        provider: "meta_pixel",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "fbq\\s*\\(\\s*['\"]init['\"]\\s*,\\s*['\"](\\d{15,16})['\"]",
        flags: "gi",
        group: 1,
        note: "inline base code; the closing quote plus {15,16} fails closed on a longer digit run rather than truncating it",
    },
    {
        key: "meta_pixel_shopify_config",
        provider: "meta_pixel",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "\\\\?\"pixel_id\\\\?\"\\s*:\\s*\\\\?\"(\\d{15,16})\\\\?\"(?=[^}]{0,200}facebook_pixel)",
        flags: "gi",
        group: 1,
        note: "Shopify webPixelsConfigList, missed entirely by the URL and fbq matchers. The {15,16} bound is what rejects the 10-digit web-pixel config id sitting immediately before the real pixel id in the same object",
    },
    {
        key: "meta_pixel_tr_url",
        provider: "meta_pixel",
        kind: "advertising",
        source: "script_src",
        phase: "markup",
        regex: "facebook\\.com\\\\?\\/tr\\\\?\\/?\\?[^\"'\\s<>]*\\bid=(\\d{15,16})\\b",
        flags: "gi",
        group: 1,
        note: "JS-free noscript img, highest priority. \\\\? before /tr crosses backslash-escaped JSON URLs in __NEXT_DATA__/Shopify blobs; scheme and www. dropped because /tr?+id= is already the whole anchor; <> excluded so a match cannot run past a tag boundary",
    },
    {
        key: "crypto_monero_bare",
        provider: "monero",
        kind: "payment",
        source: "other",
        phase: "markup",
        regex: "\\b([48][0-9AB][1-9A-HJ-NP-Za-km-z]{93})\\b",
        flags: "g",
        group: 1,
        note: "95-char standard+subaddress; [48] not [4] — a 4-only class misses every 8-prefixed address including Monero's own 888t… donation address. 106-char integrated form deliberately excluded, its payment id is mintable per-donor and would fragment one wallet",
    },
    {
        key: "monetag_verify_meta",
        provider: "monetag",
        kind: "advertising",
        source: "meta_tag",
        phase: "markup",
        regex: "<meta\\b(?=[^>]{0,300}\\bname\\s*=\\s*[\"']?monetag(?![-\\w]))(?=[^>]{0,300}[\\s\"'](?<![-\\w])content\\s*=\\s*[\"']?([0-9a-f]{32})(?![0-9a-f]))",
        flags: "gi",
        group: 1,
        rejectRegex: "^eas[0-9a-f]{6,}\\d*$",
        normalize: "lower",
        note: "same shape as the propeller meta but a separate collector — separate companies since the 2022 spin-off, and collapsing the two names would lose a real distinction",
    },
    {
        key: "monetag_zone_data_attr",
        provider: "monetag",
        kind: "advertising",
        source: "script_src",
        phase: "markup",
        regex: "<script\\b(?=[^>]{0,400}/(?:(?:tag|vignette)\\.min|sdk)\\.js)(?=[^>]{0,400}\\bdata-zone\\s*=\\s*[\"']?(\\d{4,9})(?!\\d))",
        flags: "gi",
        group: 1,
        rejectRegex: "^0+$",
        note: "two lookaheads off one <script> so attribute order is irrelevant (pat needed two alternations for that); \\bdata-zone= cannot reach ExoClick's data-zoneid=",
    },
    {
        key: "monetag_zone_dataset",
        provider: "monetag",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "\\.dataset\\.zone\\s*=\\s*[\"'](\\d{4,9})[\"'](?=(?:(?!\\.src\\s*=)[\\s\\S]){0,300}?\\.src\\s*=\\s*[\"'][^\"'<>]{0,120}/(?:(?:tag|vignette)\\.min|sdk)\\.js)",
        flags: "g",
        group: 1,
        rejectRegex: "^0+$",
        note: "injected loader; tightened past pat by requiring the vendor path inside the following .src= so reject-list rule 4 (vendor marker within the window) is satisfied rather than just a bare .src=",
    },
    {
        key: "monetag_zone_iife_arg",
        provider: "monetag",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "\\}\\)\\(\\s*[\"'][a-z0-9.-]+\\.[a-z]{2,}[\"']\\s*,\\s*([1-9]\\d{4,8})\\s*,\\s*document\\.createElement",
        flags: "gi",
        group: 1,
        note: "two-arg loader (domain, zone, document.createElement) — zone is the second positional argument, the domain argument is disposable and deliberately not captured",
    },
    {
        key: "monetag_zone_query",
        provider: "monetag",
        kind: "advertising",
        source: "script_src",
        phase: "markup",
        regex: "(?<!propu\\.sh[^\"'\\s<>]{0,60})/(?:tag|vignette)\\.min\\.js\\?(?:[^\"'\\s<>]{0,80}&(?:amp;)?)?z=(\\d{4,12})(?!\\d)",
        flags: "gi",
        group: 1,
        rejectRegex: "^0+$",
        note: "leading / kills WordPress frontend-gtag.min.js; lookbehind hands propu.sh to the PropellerAds collector, which is the only thing separating the two networks on this shape",
    },
    {
        key: "monetag_zone_sdk_path",
        provider: "monetag",
        kind: "advertising",
        source: "script_src",
        phase: "markup",
        regex: "\\bsrc\\s*=\\s*[\"']https?://[a-z0-9.-]+\\.[a-z]{2,}/40\\d/([1-9]\\d{4,8})(?=[?&\"'])",
        flags: "gi",
        group: 1,
        note: "'where' names only /400/ and /401/ as the ad-format segment, so tightened from pat's \\d{2,4}, which the entry text does not support",
    },
    {
        key: "naver_wcs_account",
        provider: "naver_analytics",
        kind: "analytics",
        source: "inline_script",
        phase: "markup",
        regex: "wcs_add\\s*(?:\\[\\s*([\"'])wa\\1\\s*\\]|\\.wa)\\s*=\\s*([\"'])((?:s_)?[0-9a-fA-F]{10,20})\\2",
        flags: "g",
        group: 3,
        normalize: "lower",
        emit: "tracking_id",
        note: "Value is bare hex, so the wcs_add[\"wa\"] / wcs_add.wa assignment is the whole anchor; one regex covers both the bare-hex and s_-prefixed key shapes since they occupy the same slot.",
    },
    {
        key: "naver_site_verification",
        provider: "naver_search_advisor",
        kind: "site_verification",
        source: "meta_tag",
        phase: "markup",
        regex: "<meta\\b(?=[^>]*\\bname=[\"']naver-site-verification[\"'])[^>]*?[\\s\"'](?<![-\\w])content=[\"']\\s*([0-9a-fA-F]{32,64})\\s*[\"']",
        flags: "gi",
        group: 1,
        normalize: "lower",
        emit: "tracking_id",
        note: "Zero-width lookahead binds name= and content= to the SAME <meta> tag in either attribute order; the hex-only class is what excludes the base64url google-site-verification sibling.",
    },
    {
        key: "onetag_kr_eid",
        provider: "onetag_kr",
        kind: "tag_manager",
        source: "script_src",
        phase: "markup",
        regex: "cdn\\.(?:onetag|datamanager)\\.co\\.kr/[^\"'<>\\s]*tcs[a-z]*\\.js\\?[^\"'<>\\s]*?\\beid=([^\"'<>&\\s\\\\]{6,64})",
        flags: "gi",
        group: 1,
        emit: "tracking_id",
        note: "Host + tcs*.js path + eid= carry all the safety since the id's charset is undocumented; backslash excluded from the value class so a JSON-escaped snippet cannot append a stray \\.",
    },
    {
        key: "patreon_bepatron_uid",
        provider: "patreon",
        kind: "payment",
        source: "html_link",
        phase: "markup",
        regex: "https?:\\/\\/(?:www\\.)?patreon\\.com\\/(?:bePatron|user)\\?(?:[^\"'\\s]*&)?u=(\\d{3,10})\\b",
        flags: "gi",
        group: 1,
        note: "numeric creator id only. (?:[^\"'\\s]*&)? anchors u= to ? or & structurally instead of trusting \\b, so cu=/ru= cannot win. The vanity /handle form is deleted deliberately — 7/7 measured false, and a denylist against a vendor route table you cannot fetch is not a fix",
    },
    {
        key: "paypal_business_email_input",
        provider: "paypal",
        kind: "payment",
        source: "other",
        phase: "markup",
        regex: "<input\\b(?=[^>]*\\bname\\s*=\\s*[\"']business[\"'])[^>]*?\\bvalue\\s*=\\s*[\"']([A-Za-z0-9._%+\\-]{1,64}@(?:[A-Za-z0-9](?:[A-Za-z0-9\\-]{0,61}[A-Za-z0-9])?\\.)+[A-Za-z]{2,24})[\"']",
        flags: "gi",
        group: 1,
        pageGuard: "<form[^>]*action\\s*=\\s*[\"'][^\"']*(?:www\\.)?paypal\\.com\\/(?:cgi-bin\\/webscr|donate)",
        reject: ["seller@designerfotos.com"],
        rejectRegex: "@(?:example|business\\.example|personal\\.example)\\.com$|^sb-|^sandbox",
        normalize: "lower",
        urldecode: true,
        emit: "email",
        note: "'where' wins over 'pat' here and the entry asks for form-BLOCK scoping; pageGuard is document-wide, the weaker approximation this schema allows — a page with a PayPal form elsewhere could leak an unrelated name=business input. Compare reject lowercased; PII, flag it",
    },
    {
        key: "paypal_business_email_link",
        provider: "paypal",
        kind: "payment",
        source: "html_link",
        phase: "markup",
        regex: "https?:\\/\\/(?:www\\.)?paypal\\.com\\/(?:cgi-bin\\/webscr|donate)\\/?[^\"'\\s>]*?[?&]business=([A-Za-z0-9._%+\\-]{1,64}(?:@|%40)(?:[A-Za-z0-9\\-]{1,63}\\.)+[A-Za-z]{2,24})",
        flags: "gi",
        group: 1,
        reject: ["seller@designerfotos.com"],
        rejectRegex: "@(?:example|business\\.example|personal\\.example)\\.com$|^sb-|^sandbox",
        normalize: "lower",
        urldecode: true,
        emit: "email",
        note: "pasted donate link — self-gating on the paypal.com host, so it is safe document-wide with no pageGuard. URL-decode %40 before emitting or the same address forms two nodes",
    },
    {
        key: "paypal_business_merchant_id_link",
        provider: "paypal",
        kind: "payment",
        source: "html_link",
        phase: "markup",
        regex: "https?:\\/\\/(?:www\\.)?paypal\\.com\\/(?:cgi-bin\\/webscr|donate)\\/?[^\"'\\s>]*?[?&]business=([A-Z0-9]{13})(?![A-Za-z0-9])",
        flags: "g",
        group: 1,
        note: "business= may legally hold the 13-char opaque merchant account id instead of an email — account-level, non-PII, cleaner shape than the email, so emit tracking_id not email. Case-sensitive throughout because JS has no (?-i:), which costs a mixed-case host",
    },
    {
        key: "paypal_hosted_button_id_input",
        provider: "paypal",
        kind: "payment",
        source: "other",
        phase: "markup",
        regex: "<input[^>]*\\bname=[\"']?hosted_button_id[\"']?[^>]*\\bvalue=[\"']?([A-Z0-9]{8,17})\\b",
        flags: "g",
        group: 1,
        note: "hidden input, natural attribute order; [^>]* confines the match to a single tag",
    },
    {
        key: "paypal_hosted_button_id_input_rev",
        provider: "paypal",
        kind: "payment",
        source: "other",
        phase: "markup",
        regex: "<input[^>]*\\bvalue=[\"']?([A-Z0-9]{8,17})[\"']?[^>]*\\bname=[\"']?hosted_button_id\\b",
        flags: "g",
        group: 1,
        note: "hidden input with reversed attribute order, the hand-written-markup case",
    },
    {
        key: "paypal_hosted_button_id_kv",
        provider: "paypal",
        kind: "payment",
        source: "other",
        phase: "markup",
        regex: "hosted_button_id[\"']?\\s*[=:]\\s*[\"']?([A-Z0-9]{8,17})\\b",
        flags: "g",
        group: 1,
        note: "URL/JSON/inline form. No [?&] anchor, so an HTML-escaped &amp; still matches. Do not require cmd=_s-xclick or the cgi-bin action — the modern paypal.com/donate/?hosted_button_id= link has neither",
    },
    {
        key: "paypal_sdk_client_id",
        provider: "paypal",
        kind: "payment",
        source: "script_src",
        phase: "markup",
        regex: "https?:\\/\\/www\\.paypal\\.com\\/sdk\\/js\\?(?![^\"'\\s]*[?&;]merchant-id=)(?:[^\"'\\s]*?[&;])?client-id=([A-Za-z0-9_-]{20,120})",
        flags: "g",
        group: 1,
        note: "the negative lookahead drops platform-hub URLs carrying merchant-id=; the ?/&/; separator requirement is what stops merchant-client-id= and data-client-id= matching, which the entry's \\b did not. Post-filter not expressible here: drop the match if the enclosing <script> carries data-partner-attribution-id",
    },
    {
        key: "paypal_v6_client_id",
        provider: "paypal",
        kind: "payment",
        source: "inline_script",
        phase: "markup",
        regex: "clientId\\s*:\\s*[\"']([A-Za-z0-9_-]{20,120})[\"']",
        flags: "g",
        group: 1,
        pageGuard: "paypal\\.com\\/web-sdk\\/v6\\/core",
        note: "ungated this fires on every OAuth/Auth0/Google/MSAL config blob on the web; the page-level v6 gate is the only thing making it shippable",
    },
    {
        key: "plausible_data_domain",
        provider: "plausible",
        kind: "analytics",
        source: "script_src",
        phase: "markup",
        regex: "<script\\b(?=[^>]*(?:plausible|\\/js\\/script))[^>]*\\bdata-domain\\s*=\\s*[\"']([^\"']{4,300})[\"']",
        flags: "gi",
        group: 1,
        reject: ["example.com", "yourdomain.com", "yourwebsite.com", "mywebsite.com", "domain.com", "dummy.site", "plausible.io"],
        note: "the lookahead scans the WHOLE tag, so attribute order does not matter and there is no 300-char cap to lose a tag carrying a CSP nonce. Post-processing not expressible here: split the capture on comma, lowercase, shape-gate ^[a-z0-9-]+(\\.[a-z0-9-]+)+$, drop the fetched host itself — what survives IS the copied-tag evidence",
    },
    {
        key: "plausible_pa_token",
        provider: "plausible",
        kind: "analytics",
        source: "script_src",
        phase: "markup",
        regex: "https?:\\/\\/plausible\\.io\\/js\\/(pa-[A-Za-z0-9_-]{10,64})\\.js\\b",
        flags: "g",
        group: 1,
        note: "emit WITH the pa- prefix, the prefix names the provider. The plausible.io host anchor is mandatory — host-agnostic /js/pa-*.js fires on ordinary bundle filenames. Token is per-SITE, not per-account; do not fetch the script to resolve its baked domain",
    },
    {
        key: "plugrush_prset_domain",
        provider: "plugrush",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "_prset\\s*\\.\\s*push\\s*\\(\\s*\\[\\s*(?:[\"']|&(?:quot|apos|#0*3[49]);)domain(?:[\"']|&(?:quot|apos|#0*3[49]);)\\s*,\\s*(?:[\"']|&(?:quot|apos|#0*3[49]);)([a-z0-9][a-z0-9.-]*\\.[a-z]{2,})(?:[\"']|&(?:quot|apos|#0*3[49]);)",
        flags: "gi",
        group: 1,
        reject: ["example.com", "yourdomain.com", "domain.com", "alwingulla.com", "effectivecpmnetwork.com", "heavenlywhile.com", "5gvci.com", "shoukigaigoors.net", "stootsou.net", "fenoofaussut.net", "gizokraijaw.net", "vemtoutcheeg.com", "nap5k.com"],
        note: "the value is the operator-DECLARED domain, not a serving host, so reject-list rule 3 is deliberately not applied wholesale — only placeholders plus the documented rotating serving hosts are denied",
    },
    {
        key: "plugrush_prverify_meta",
        provider: "plugrush",
        kind: "advertising",
        source: "meta_tag",
        phase: "markup",
        regex: "<meta\\b(?=[^>]{0,300}\\bname\\s*=\\s*[\"']?prVerify(?![-\\w]))(?=[^>]{0,300}[\\s\"'](?<![-\\w])content\\s*=\\s*[\"']?([0-9a-f]{32})(?![0-9a-f]))",
        flags: "gi",
        group: 1,
        rejectRegex: "^eas[0-9a-f]{6,}\\d*$",
        normalize: "lower",
        note: "order-independent lookaheads because 2 of the 3 live pages emit content= BEFORE name=; (?![0-9a-f]) stops a 40/64-hex value truncating to a plausible-looking 32",
    },
    {
        key: "popads_siteid",
        provider: "popads",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "_pop\\b[\\s\\S]{0,200}?[\"']siteId[\"']\\s*,\\s*[\"']?(\\d{5,9})(?!\\d)",
        flags: "g",
        group: 1,
        rejectRegex: "^0+$",
        note: "case-SENSITIVE, and siteId must be quoted — that pair is what keeps Matomo _paq setSiteId and JWPlayer siteID out",
    },
    {
        key: "popcash_uid",
        provider: "popcash_publisher",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "\\bvar\\s+uid\\s*=\\s*[\"'](\\d{4,9})[\"'](?:(?<=popcash\\.net[\\s\\S]{0,340})|(?=[\\s\\S]{0,300}?popcash\\.net))",
        flags: "g",
        group: 1,
        rejectRegex: "^0+$",
        note: "var uid is a catastrophically common name, so popcash.net is required within ~300 chars on EITHER side, expressed as one lookbehind|lookahead alternation to keep a single capture group",
    },
    {
        key: "popcash_wid",
        provider: "popcash_site",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "\\bwid\\s*[:=]\\s*[\"'](\\d{4,9})[\"'](?:(?<=popcash\\.net[\\s\\S]{0,340})|(?=[\\s\\S]{0,300}?popcash\\.net/(?:pop|show)\\.js))",
        flags: "g",
        group: 1,
        rejectRegex: "^0+$",
        note: "DIVERGES FROM pat: 'where' says same anchoring requirement as uid (either direction) while pat only had the forward one, so the reverse lookbehind branch is added per 'where'",
    },
    {
        key: "propellerads_verify_meta",
        provider: "propellerads",
        kind: "advertising",
        source: "meta_tag",
        phase: "markup",
        regex: "<meta\\b(?=[^>]{0,300}\\bname\\s*=\\s*[\"']?propeller\\b)(?=[^>]{0,300}\\bcontent\\s*=\\s*[\"']?([0-9a-f]{32})(?![0-9a-f]))",
        flags: "gi",
        group: 1,
        rejectRegex: "^eas[0-9a-f]{6,}\\d*$",
        normalize: "lower",
        note: "bare name=propeller with no -site-verification suffix; split out from the monetag meta so the provider slug is a literal instead of a group-derived guess",
    },
    {
        key: "propellerads_zone_propush",
        provider: "propellerads",
        kind: "advertising",
        source: "script_src",
        phase: "markup",
        regex: "\\bpropu\\.sh[/\\\\][/\\\\a-z0-9.\\-_]*tag\\.min\\.js[^\"'\\s<>]*[?&](?:amp;)?z=(\\d{5,9})(?!\\d)",
        flags: "gi",
        group: 1,
        rejectRegex: "^0+$",
        note: "the propu.sh path is the only separator from Monetag's identical tag.min.js?z= shape, and the shared zone number space is not theoretical here",
    },
    {
        key: "reddit_pixel_rdt_init",
        provider: "reddit",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "\\brdt\\(\\s*['\"]init['\"]\\s*,\\s*['\"](t2_[a-z0-9]{4,16})['\"]",
        flags: "g",
        group: 1,
        note: "the t2_ prefix makes it self-identifying and zero-collision; the value is a Reddit account fullname, so it names a lookupable account rather than merely linking two sites",
    },
    {
        key: "richads_pubid",
        provider: "richads_publisher",
        kind: "advertising",
        source: "script_src",
        phase: "markup",
        regex: "\\brichinfo\\.co/[^\\s\"'<>`]{0,200}?[?&](?:amp;)?pubid=(\\d{4,9})(?!\\d)",
        flags: "gi",
        group: 1,
        rejectRegex: "^0+$",
        note: "host is richinfo.co, not richads.com; a bare pubid= would collide with unrelated widget query strings",
    },
    {
        key: "richads_siteid",
        provider: "richads_site",
        kind: "advertising",
        source: "script_src",
        phase: "markup",
        regex: "(?:(?<![\\w-])richinfo\\.co/[^\"'\\s<>]{0,200}[?&](?:amp;)?siteid=|<script\\b(?=[^>]{0,400}(?<![\\w-])richinfo\\.co)[^>]{0,400}?\\bdata-siteid\\s*=\\s*[\"']|RichPartners\\s*\\.\\s*init\\s*\\(\\s*\\{[^{}]{0,300}?[\"']siteid[\"']\\s*:\\s*[\"']?)(\\d{4,9})(?!\\d)",
        flags: "gi",
        group: 1,
        rejectRegex: "^0+$",
        note: "pat's three alternations refolded as a non-capturing PREFIX alternation with one shared trailing capture, so a single group index holds the value; every branch still requires richinfo.co or RichPartners.init",
    },
    {
        key: "shareasale_publisher_id",
        provider: "shareasale",
        kind: "affiliate",
        source: "html_link",
        phase: "markup",
        regex: "https?:\\/\\/(?:www\\.)?shareasale\\.com\\/[a-z0-9-]{1,12}\\.cfm\\?(?:[^\"'\\s<>]*?[&;])?(?:u|userID|userid)=(\\d{3,9})(?!\\d)",
        flags: "g",
        group: 1,
        note: "a real query separator is required because afftrack= is publisher-controlled free text, so \\bu= captures ...&afftrack=camp-u=999999. Path class widened for m-pr.cfm and the param alternation covers its userID= spelling. m= is the merchant, never the account",
    },
    {
        key: "snapchat_snaptr_init",
        provider: "snapchat",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "\\bsnaptr\\s*\\(\\s*['\"]init['\"]\\s*,\\s*['\"]([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})['\"]",
        flags: "g",
        group: 1,
        reject: ["6abc82ca-4a3a-4391-98ba-0317a8471234"],
        normalize: "lower",
        note: "the snaptr('init' anchor is mandatory — a bare UUID in markup could be anything. Vendor-doc-confirmed, not field-confirmed",
    },
    {
        key: "statcounter_noscript_img",
        provider: "statcounter",
        kind: "analytics",
        source: "script_src",
        phase: "markup",
        regex: "(?:https?:)?\\/\\/c\\d*\\.statcounter\\.com\\/(\\d{4,9})\\/\\d+\\/([0-9a-f]{8})\\/",
        flags: "g",
        group: 1,
        note: "JS-free noscript img, the preferred shape: it carries project+security as one tuple. c\\d* covers the legacy c1/c2 hosts a decade-old mirror template would use. Group 2 (sc_security) is a GUARD ONLY — 8 hex collides freely and must never become a node",
    },
    {
        key: "statcounter_sc_project_inline",
        provider: "statcounter",
        kind: "analytics",
        source: "inline_script",
        phase: "markup",
        regex: "\\bsc_project\\s*=\\s*[\"']?(\\d{4,9})\\b",
        flags: "g",
        group: 1,
        note: "\\b terminator plus optional quote: the entry's \\s*; form misses both of the commonest real variants",
    },
    {
        key: "stripe_publishable_key",
        provider: "stripe",
        kind: "payment",
        source: "other",
        phase: "markup",
        regex: "(pk_live_[A-Za-z0-9]{24,247})(?![A-Za-z0-9])",
        flags: "g",
        group: 1,
        note: "the pk_live_ literal is a strong enough anchor that a document-wide sweep is safe (this is not a bare digit/hex sweep). The modern key embeds the acct_ stem, so a shared key is a shared, subpoenable merchant",
    },
    {
        key: "tenping_media_id",
        provider: "tenping",
        kind: "affiliate",
        source: "other",
        phase: "markup",
        regex: "<tenping\\b[^>]*[\\s\"']mediaid\\s*=\\s*[\"']?(\\d{5,12})\\b",
        flags: "gi",
        group: 1,
        emit: "tracking_id",
        note: "Bound to the <tenping> custom element so the digits are never swept bare; the opaque tenping-ad-display-type blob is deliberately not captured.",
    },
    {
        key: "tiktok_sdkid_url",
        provider: "tiktok_pixel",
        kind: "advertising",
        source: "script_src",
        phase: "markup",
        regex: "analytics\\.tiktok\\.com\\/i18n\\/pixel\\/(?:events|sdk)\\.js\\?(?:[^\"'\\s]*?[?&])?sdkid=([A-Z0-9]{18,24})\\b",
        flags: "g",
        group: 1,
        reject: ["XXXXXXXXXXXXXXXXXXXX"],
        rejectRegex: "^(.)\\1+$",
        note: "CORRECTED the entry's pat: it consumed the ? then required a second [?&], so it could not match sdk.js?sdkid=… — the exact form 'where' documents as verified on gfuel.com. Separator group made optional; protocol-relative // allowed",
    },
    {
        key: "tiktok_ttq_load",
        provider: "tiktok_pixel",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "ttq\\.load\\(\\s*(['\"])([A-Z0-9]{18,24})\\1",
        flags: "g",
        group: 2,
        reject: ["XXXXXXXXXXXXXXXXXXXX"],
        rejectRegex: "^(.)\\1+$",
        note: "the quote is backreferenced so ttq.load('ABC\") cannot match. Emit-time guard beyond any regex: drop a value with fewer than 4 distinct characters — the rejectRegex only catches the all-one-char case",
    },
    {
        key: "trafficstars_spot",
        provider: "trafficstars",
        kind: "advertising",
        source: "script_src",
        phase: "markup",
        regex: "(?:<script[^>]*cdn\\.tsyndicate\\.com[^>]*\\sdata-id\\s*=\\s*[\"']?|data-ts-spot\\s*=\\s*[\"']?|tsyndicate\\.com/(?:api/v1/direct|do2)/|TS(?:Popunder|MasterSpot|VideoInstantMessage|OutstreamVideo)\\s*(?:\\(|%28)[\\s\\S]{0,300}?spot(?:\\s*:\\s*[\"']|%3A(?:%20|\\s)*%22))([0-9a-fA-F]{32})(?![0-9a-fA-F])",
        flags: "g",
        group: 1,
        pageGuard: "tsyndicate",
        rejectRegex: "^eas[0-9a-f]{6,}\\d*$",
        normalize: "lower",
        note: "bare spot:\"<32hex>\" is not distinctive so the whole collector is page-gated on tsyndicate; the %3A/%22 branch exists because the live call ships percent-encoded inside a data:text/javascript src, which the raw-body pattern would otherwise miss",
    },
    {
        key: "twitter_twq_event_tag",
        provider: "twitter_pixel",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "\\btwq\\(\\s*['\"]event['\"]\\s*,\\s*['\"]tw-([a-z0-9]{4,8})-[a-z0-9]{4,8}['\"]",
        flags: "gi",
        group: 1,
        note: "newer event form tw-<pixelid>-<eventid>; only the first segment is the tag id, the second belongs to the conversion event. Same value space as twq('init'",
    },
    {
        key: "twitter_twq_init",
        provider: "twitter_pixel",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "\\btwq\\(\\s*['\"](?:init|config)['\"]\\s*,\\s*['\"]([a-z0-9]{4,8})['\"]",
        flags: "gi",
        group: 1,
        note: "5-6 base36 chars is far too short to recognise alone — the twq( call is the whole anchor and a bare 'o54rb' must never match",
    },
    {
        key: "umami_data_website_id",
        provider: "umami",
        kind: "analytics",
        source: "script_src",
        phase: "markup",
        regex: "data-website-id\\\\?[\"']?\\s*[:=]\\s*\\\\?[\"']?([0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12})",
        flags: "g",
        group: 1,
        normalize: "lower",
        note: "plain script attribute, present in served markup with no JS — the best-behaved collector in this family. Capture the script's src host separately at emit time: a self-hosted Umami is itself an infrastructure pivot",
    },
    {
        key: "unknown_esnk_zone",
        provider: "unknown_esnk",
        kind: "advertising",
        source: "script_src",
        phase: "markup",
        regex: "/lv/esnk/(\\d{5,9})/code\\.js",
        flags: "gi",
        group: 1,
        rejectRegex: "^0+$",
        note: "entry 5 says attribution is UNCONFIRMED (Clickadu vs ClickAdilla), so the namespace stays unknown_esnk rather than baking a guess into node identity that would be wrong forever",
    },
    {
        key: "widerplanet_advertiser",
        provider: "widerplanet",
        kind: "advertising",
        source: "inline_script",
        phase: "markup",
        regex: "wp(?:_conf|tg_tagscript_vars)\\b[\\s\\S]{0,300}?\\bti[\"']?\\s*[=:]\\s*[\"']?(\\d{3,10})\\b",
        flags: "g",
        group: 1,
        emit: "tracking_id",
        note: "Two-letter key ti= is only safe inside a bounded 300-char window opened by the vendor-specific wp_conf / wptg_tagscript_vars variable name.",
    },
    {
        key: "yandex_metrica_watch",
        provider: "yandex_metrica",
        kind: "analytics",
        source: "html_link",
        phase: "markup",
        regex: "\\bmc\\.yandex\\.(?:ru|com)/watch/(\\d{5,10})\\b",
        flags: "gi",
        group: 1,
        emit: "tracking_id",
        note: "The <noscript> fallback pixel URL — literal served bytes, needs no JS execution; /watch/ excludes the /informer/ badge by construction.",
    },
    {
        key: "yandex_metrica_ym_init",
        provider: "yandex_metrica",
        kind: "analytics",
        source: "inline_script",
        phase: "markup",
        regex: "\\bym\\(\\s*(\\d{5,10})\\s*,\\s*([\"'])init\\2",
        flags: "gi",
        group: 1,
        emit: "tracking_id",
        note: "Second shape for pages that dropped the noscript pixel; the literal \"init\" second argument is what stops a 2-char minified ym( call from matching.",
    },
    {
        key: "crypto_payment_uri",
        provider: "",
        providerFromGroup: 1,
        kind: "payment",
        source: "html_link",
        phase: "markup",
        regex: "\\b(bitcoin|bitcoincash|ethereum|litecoin|dogecoin|monero):([A-Za-z0-9]{20,120})(?=[?\"'\\s<&#]|$)",
        flags: "gi",
        group: 2,
        note: "scheme-anchored, query string excluded by the lookahead. Value is the BARE address (group 2) so it converges with the bare matchers onto ONE node; the chain rides in provider (lowercase it) — emitting 'bitcoin:bc1q…' here would split one wallet across two nodes",
    },
    {
        key: "matomo_paq_setsiteid",
        provider: "",
        providerFromGroup: 1,
        kind: "analytics",
        source: "inline_script",
        phase: "markup",
        regex: "[\"'](?:https?:)?\\/\\/([A-Za-z0-9.-]+(?::\\d+)?(?:\\/[\\w.~%-]+)*)\\/[\"'][^<]{0,400}?_paq\\.push\\(\\s*\\[\\s*[\"']setSiteId[\"']\\s*,\\s*[\"']?(\\d{1,8})",
        flags: "g",
        group: 2,
        pageGuard: "(?:matomo|piwik)\\.(?:php|js)|\\/js\\/container_",
        note: "idSite is worthless bare (CNIL, a real government install, is idSite 1) so the tracker host rides as the runtime provider — that IS the entry's required tuple, expressed with providerFromGroup. [^<] cannot escape the script block. At emit: lowercase the host, and if it is cdn.matomo.cloud replace it with its first path segment",
    },
    {
        key: "matomo_php_idsite_url",
        provider: "",
        providerFromGroup: 1,
        kind: "analytics",
        source: "script_src",
        phase: "markup",
        regex: "(?:https?:)?\\/\\/([A-Za-z0-9.-]+(?:\\/[\\w.~%-]+)*)\\/(?:matomo|piwik)\\.php\\?idsite=(\\d{1,8})(?![0-9])",
        flags: "gi",
        group: 2,
        note: "Matomo Image Tracking Link — host and idsite contiguous in one literal, so the tuple needs no window. idsite must be the first param, which is how Matomo generates these",
    },
    {
        key: "assetlinks_android_package",
        provider: "android_app",
        kind: "other",
        source: "well_known",
        phase: "wellknown",
        regex: "\"package_name\"\\s*:\\s*\"([A-Za-z][A-Za-z0-9_]*(?:\\.[A-Za-z0-9_]+)+)\"",
        flags: "g",
        group: 1,
        pageGuard: "\"namespace\"\\s*:\\s*\"android_app\"",
        note: "Key-anchored with \\s* not [ \\t]* so pretty-printed files match, and [A-Za-z] not [a-z] so com.netflix.NGP.Pandora / kr.co.captv.pooqV2 survive without needing the i flag.",
    },
    {
        key: "assetlinks_sha256_cert",
        provider: "android_cert_sha256",
        kind: "other",
        source: "well_known",
        phase: "wellknown",
        regex: "(?<![0-9A-Fa-f:])((?:[0-9A-Fa-f]{2}:){31}[0-9A-Fa-f]{2})(?![0-9A-Fa-f:])",
        flags: "g",
        group: 1,
        pageGuard: "\"namespace\"\\s*:\\s*\"android_app\"",
        normalize: "lower",
        note: "Colon-hex boundary lookarounds anchor the byte count exactly, so a 64-byte SHA-512 token cannot be carved into two bogus 32-byte fingerprints.",
    },
    {
        key: "aasa_apple_team_id",
        provider: "apple",
        kind: "other",
        source: "well_known",
        phase: "wellknown",
        regex: "\"([A-Z0-9]{10})\\.[A-Za-z0-9](?:[A-Za-z0-9._-]{0,126}[A-Za-z0-9])?\"",
        flags: "g",
        group: 1,
        pageGuard: "\"(?:applinks|webcredentials|activitycontinuation|appclips)\"\\s*:",
        note: "Quoted TEAMID.bundle string is the anchor; case-SENSITIVE (no i) or the 10-char class matches any token, and the AASA-key pageGuard keeps it off every other fetched JSON.",
    },
    {
        key: "bing_site_auth_user",
        provider: "bing_webmaster",
        kind: "site_verification",
        source: "well_known",
        phase: "wellknown",
        regex: "<user(?:\\s[^>]*)?>\\s*([0-9A-Fa-f]{32})\\s*</user>",
        flags: "gi",
        group: 1,
        pageGuard: "^﻿?\\s{0,200}(?:<\\?xml[^?>]{0,200}\\?>\\s{0,200})?(?:<!--(?:[^-]|-(?!->)){0,4000}-->\\s{0,200}){0,5}<users(?:\\s[^>]{0,200})?>",
        normalize: "lower",
        note: "Path is /BingSiteAuth.xml (not /.well-known/, phase wellknown is the closest bucket); the <users> root guard is the real fetch check since content-type varies xml/text-xml/octet-stream.",
    },
    {
        key: "msft_identity_application_id",
        provider: "entra",
        kind: "other",
        source: "well_known",
        phase: "wellknown",
        regex: "\"applicationId\"\\s*:\\s*\"([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})\"",
        flags: "g",
        group: 1,
        pageGuard: "\"associatedApplications\"\\s*:",
        reject: ["00000000-0000-0000-0000-000000000000", "00000000-1111-2222-3333-444444444444"],
        rejectRegex: "-c000-000000000000$",
        normalize: "lower",
        note: "Key-anchored GUID; guard pins it to the association file, and the reject pair plus -c000- suffix drops the nil GUID, the Microsoft-docs placeholder and every MS first-party app id.",
    },];
